// AUTO-GENERATED by scripts/fetch-osm.mjs — do not edit by hand.
// Equirectangular projection of central Gothenburg. 1 unit == 1 metre; North is -Z.
export const GEO_META = {
  bbox: { s: 57.68, w: 11.915, n: 57.725, e: 12.015 },
  lat0: 57.7025,
  lon0: 11.965,
  mPerDegLat: 111194.92664455873,
  mPerDegLon: 59413.16919993794,
} as const;

/** Project WGS84 lon/lat to local world metres (x east, z south). */
export function project(lon: number, lat: number): { x: number; z: number } {
  return {
    x: (lon - GEO_META.lon0) * GEO_META.mPerDegLon,
    z: -(lat - GEO_META.lat0) * GEO_META.mPerDegLat,
  };
}

/** Half-extents of the world in metres. */
export const WORLD_HALF_X = ((GEO_META.bbox.e - GEO_META.bbox.w) / 2) * GEO_META.mPerDegLon;
export const WORLD_HALF_Z = ((GEO_META.bbox.n - GEO_META.bbox.s) / 2) * GEO_META.mPerDegLat;
